# Project name.
PROJECT_NAME := hello-llvm
PROJ_VERSION := 0.1
 
# Set this variable to the top of the LLVM source tree.
LLVM_SRC_ROOT = /home/mminutoli/projects/llvm/src

# Set this variable to the top level directory where LLVM was built.
# (this is *not* the same as OBJ_ROOT as defined in LLVM's Makefile.config).
LLVM_OBJ_ROOT = /home/mminutoli/projects/llvm/src

# Set the directory root of this project's source files.
PROJ_SRC_ROOT := $(subst //,/,/home/mminutoli/projects/llvm/src/projects/code-morphing)

# Set the root directory of this project's object files.
PROJ_OBJ_ROOT := $(subst //,/,@abs_top_objdir@)

# Set the root directory of this project's install prefix.
PROJ_INSTALL_ROOT := /usr/local
