##===- tools/COTPasses/Makefile ----------------------------*- Makefile -*-===##

LEVEL = ../..

LIBRARYNAME = CMPasses

LOADABLE_MODULE = 1

USEDLIBS = CodeMorphing.a

include $(LEVEL)/Makefile.common
